### ISSUE TITLE
Maintain a fork ?

### ISSUE THREAD

**Issue by flibustenet** [phpdave11/gofpdf#1]
Hi,

Would you like to maintain a fork of gofpdf ? I cannot do it myself but i could help.

**Comment by phpdave11** [comment]
Yes.  Since jung-kurt archived gofpdf I forked it to make updates to gofpdi (my pdf document importer library.)

I’m not sure how much actual work I will be able to do on the library itself, but I am willing to accept pull requests, look into issues, etc.

**Comment by maxekman** [comment]
Would it be possible for you to maintain the actual original package instead of a fork?

**Comment by phpdave11** [comment]
No.  Kurt Jung has archived his repositories and I believe he was the only maintainer.

**Comment by maxekman** [comment]
Alright, I’ll use your fork then. Looks like the best option! 🙂

**Comment by Anaphylaxis** [comment]
> Yes. Since jung-kurt archived gofpdf I forked it to make updates to gofpdi (my pdf document importer library.)
> 
> I’m not sure how much actual work I will be able to do on the library itself, but I am willing to accept pull requests, look into issues, etc.

Other than removing jung-kurt's name and inserting yours, what changes have you made to this package? https://github.com/jung-kurt/gofpdf/compare/master...phpdave11:gofpdf:master
